### ISSUE TITLE
Having an issue with the building 

### ISSUE THREAD

**Issue by northkode** [kd8ssq/cordova-plugin-app-icon-changer#1]
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  /Users/projects/SA_PLATFORM/app/platforms/android/app/src/main/res/xml/config.xml:155: error: unbound prefix.

Line 155 of res/config.xml:
```
<edit-config file="AndroidManifest.xml" mode="overwrite" target="/manifest/application/activity[@android:name='MainActivity']">
        <activity android:name="MainActivity" />
    </edit-config>
```

**Comment by northkode** [comment]
Looks like having this in the main config.xml file is what is breaking it 

<config-file target="AndroidManifest.xml" parent="application">

            <activity-alias
                   android:enabled="false"
                   android:name="org.apache.cordova.appiconchanger.MainActivity__homedepot"
                   android:icon="@drawable/homedepot"
                   android:label="Homedepot"
                   android:targetActivity=".MainActivity">
                   <intent-filter>
                       <action android:name="android.intent.action.MAIN" />
                       <category android:name="android.intent.category.LAUNCHER" />
                   </intent-filter>
               </activity-alias>

</config-file>

Cordova writes this into the res/xml/config.xml and it is causing it to break

**Comment by northkode** [comment]
I'm also having an issue where if you remove this line

```
        <category android:name="android.intent.category.LAUNCHER"/>
```

Cordova wont build anymore and complains

```
Cannot read property '$' of undefined
```

**Comment by kd8ssq** [comment]
Some of those issues sound very familiar.  Try removing and re-adding your android platform.  I've found any time I make changes to the config.xml file regarding the custom icons you have to remove and re-add the platform to make sure everything is updated properly.

**Comment by northkode** [comment]
Do you have an example of a working version?

I'm also wondering if the removing of the launcher causes other plugins to not play nice. Trying to think of the easiest way to do this that wont effect other plugins as well.

**Comment by kd8ssq** [comment]
While I was working on setting up a basic working version, I did discover I forgot to add something to the instructions.  

The `xmlns:android="http://schemas.android.com/apk/res/android"` attribute should be added to the root tag inside the config.xml.

So it should look something like `<widget id="io.cordova.hellocordova" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android">`

**Comment by northkode** [comment]
@kd8ssq  i JUST added that as i was doing some research and that resolves the config.xml issue!

However, removing the 
```
<intent-filter android:label="@string/launcher_name">
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/> <- remove this line from the main activity and it breaks cordova 8.0.0, not sure why
      </intent-filter>
```

Build error is  `Cannot read property '$' of undefined`

If i leave the launcher category in there, the application works and the plugin works and shows the nice dialog saying the icon changed, however it doesn't actually change. I'm assuming that is because the launcher is taking over the default icon logic

**Comment by kd8ssq** [comment]
Are you using the branch-cordova-sdk plugin?

**Comment by northkode** [comment]
@kd8ssq yes we are..

**Comment by kd8ssq** [comment]
I know what the problem is.  I'm using that as well and I had to make a handful of changes to their plugin in order to make mine work.  

They try to locate the main activity by looking for the MAIN and LAUNCHER intent filters.  But as you've seen, if you leave the LAUNCHER intent, you can't change the icon properly (I can't recall if it creates a duplicate app icon or if it always defaults to the MainActivity launcher).  

I also had to remove one of their functions which changes the MainActivity launch option because it was causing a problem with the phonegap-plugin-push plugin where push notifications received in the background would not open the app.

I got tired of trying to remember all the changes, so I just forked their plugin and put my changes in there.  You're welcome to take a look.  https://github.com/kd8ssq/cordova-ionic-phonegap-branch-deep-linking-attribution

Now I see why no one else has built the ability for Android icon changes into a cordova plugin.  There's a whole lot of moving parts that can easily conflict with other plugins.

**Comment by northkode** [comment]
@kd8ssq Perfect, thanks for the replies, Ill do some digging and check it out!

**Comment by kd8ssq** [comment]
You're welcome

**Comment by northkode** [comment]
@kd8ssq  i think i'm super close, got it to build, 
but the icon doesnt open the app, only opens the "app info" 

Here is my settings for the alias
```
<resource-file src="res/orgIcons/org1.png" target="app/src/main/res/drawable/orgIcon.png" />

        <config-file parent="/*" target="res/values/strings.xml">
            <string name="default_icon_id">fc_icon_default</string>
        </config-file>

<activity-alias android:configChanges="orientation|screenSize" android:enabled="false" android:icon="@drawable/orgIcon" android:label="@string/app_name" android:name="org.apache.cordova.appiconchanger.MainActivity__orgIcon" android:noHistory="true" android:targetActivity=".MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity-alias>
    <activity-alias android:configChanges="orientation|screenSize" android:enabled="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:name="org.apache.cordova.appiconchanger.MainActivity__fc_icon_default" android:noHistory="true" android:targetActivity=".MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity-alias>
```
It also doesnt seem to "change it" but when I swipe up on my app, the app in the background shows a default android icon instead of my app icon
Any thing stand out that might be wrong?

**Comment by kd8ssq** [comment]
Are the activity-alias nodes wrapped inside of a "config-file" node?

```
<config-file target="AndroidManifest.xml" parent="application">
	<activity-alias 
		android:enabled="false" 
		android:name="org.apache.cordova.appiconchanger.MainActivity__fc_icon_4071" 
		android:icon="@drawable/fc_icon_4071" 
		android:label="@string/app_name" 
		android:targetActivity=".MainActivity" 
		android:configChanges="orientation|screenSize" 
		android:noHistory="true">
		<intent-filter>
			<action android:name="android.intent.action.MAIN" />
			<category android:name="android.intent.category.LAUNCHER" />
		</intent-filter>
	</activity-alias>

	<!-- the default activity -->
	<activity-alias 
		android:enabled="true" 
		android:name="org.apache.cordova.appiconchanger.MainActivity__fc_icon_default" 
		android:icon="@mipmap/ic_launcher" 
		android:label="@string/app_name" 
		android:targetActivity=".MainActivity" 
		android:configChanges="orientation|screenSize" 
		android:noHistory="true">
		<intent-filter>
			<action android:name="android.intent.action.MAIN"/>
			<category android:name="android.intent.category.LAUNCHER"/>
		</intent-filter>
	</activity-alias>
</config-file>
```

**Comment by northkode** [comment]
yes, they are and i can see them in the actual AndroidManifest.xml file so the registration seems to be their. 

I am using the ic_launcher icons with normal cordova .png files. 

The string.xml file contains
```
<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="app_name">Smart Access</string>
    <string name="launcher_name">@string/app_name</string>
    <string name="activity_name">@string/launcher_name</string>
    <string name="default_icon_id">fc_icon_default</string>
</resources>
```

Not really clear if fc_icon_default is the right name or what that means?

**Comment by kd8ssq** [comment]
If I recall, the default_icon_id is just a reference so the JAVA code can easily reference whatever you're using as your launcher icons.  You should be able to set the default_icon_id to whatever you want as long as you update the default activity-alias name as well.

I think you need to change your icon reference.  Right now your resource target points to "orgIcon.png" and the android:name points to "MainActivity__orgIcon" but your activity-alias android:icon points to "@drawable/homedepot".  I think they all need to match.  

Try testing by changing homedepot to orgIcon and see what that does.

**Comment by northkode** [comment]
@kd8ssq sorry that was a typo, i just changed the homedepot part and for some reason it still doesnt change, however the Success Dialog loads the correct asset logo,

But more importantly the icon on the launcher will not open the app, it just goes to app info which tells me for some reason android doesnt know my alias is enabled to use the intent with launcher in it.. :(

Sorry for all the questions, having this feature for us would be a big win so i'm hoping I can get this to work.

**Comment by kd8ssq** [comment]
No worries.  We'll figure it out.  I have it working with over 1000 icons.

While I think about it, I did throw together a test app.  It's just a simple 2 button test to see the changes.  You'll have to add your platform and then build it.

https://github.com/kd8ssq/cordova-app-icon-changer-test

**Comment by northkode** [comment]
Ok, a bit more fiddling, if I remove my app, reinstall, create a short cut on the launcher the icon now opens the app, if I call  the changeIcon function it says success ( shows the icon in the dialog) however it doesnt update and the launcher shortcut now breaks and wont open my app, so something is getting its wires cross, with a name or something. 

Ok, ill try the sample app. Thanks

**Comment by kd8ssq** [comment]
Are you trying to use the Android emulator in Android Studio or cordova emulate android?  I always did my testing in Android Studio and I found that once you call the iconChange function and the activity was changed, if you try to run the code again in Android Studio, it will build and then throw an error saying that the "activity doesn't exist" or something like that.  It did load the new build it just can't open the app because Android Studio seems to be hardcoded to look for the primary activity, not an activity-alias.  It doesn't do this when you test on a device, just when using Android Studio.

I know when the icon change function is triggered, due to something in Android, the change can take from 5-7 seconds before it actually happens (it will also delete any shortcut you have on your home screen because the activity changes).

**Comment by northkode** [comment]
I'm not using any emulation or android studio, building straight to a test device. 

I got your sample running and works like a charm and the icon on my pixel switches instantly.. however.. my code looks exactly like yours lol Only difference is i have a bunch of plugins. 

I might start from scratch and copy from your sample and work backwards and see if i can get it working.  
Thanks again for all the help, ill keep you posted if you dont mind as I work through this!

**Comment by kd8ssq** [comment]
Sounds good.  I look forward to hearing of your progress.

I know I had mine all working till I started going through and testing all my other plugins and found a handful of conflicts, specifically around the Branch plugin and the Push Notifications plugin and I had to do the same thing you're doing.  Add 1 plugin at a time till I found which one broke something.

Good luck!

**Comment by northkode** [comment]
No idea really what I changed, other then changing the name of my icons and changing the size to a bit bigger to match the ones in your demo and now it works. 

Thanks for the support and the work on this plugin!

**Comment by kd8ssq** [comment]
Awesome!  Glad to hear!  I found that happened to me quite a bit.  My
fallback is always to remove and re-add the platform (or delete and
re-deploy the app) and most of the time it works.

Glad you were able to get it all figured out.
